# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 127) do

  create_table "addresses", :force => true do |t|
    t.column "location_id",    :integer
    t.column "street_address", :string
    t.column "description",    :text
    t.column "city",           :string
    t.column "state_id",       :integer
    t.column "zip",            :string
  end

  add_index "addresses", ["location_id"], :name => "index_addresses_on_location_id"
  add_index "addresses", ["state_id"], :name => "index_addresses_on_state_id"

  create_table "application_servers", :force => true do |t|
    t.column "application_id",    :integer
    t.column "server_id",         :integer
    t.column "service_status_id", :integer
    t.column "service_id",        :integer
  end

  add_index "application_servers", ["application_id"], :name => "index_application_servers_on_application_id"
  add_index "application_servers", ["server_id"], :name => "index_application_servers_on_server_id"
  add_index "application_servers", ["service_status_id"], :name => "index_application_servers_on_service_status_id"
  add_index "application_servers", ["service_id"], :name => "index_application_servers_on_service_id"

  create_table "apps", :force => true do |t|
    t.column "name",          :string
    t.column "short_name",    :string
    t.column "description",   :text
    t.column "department_id", :integer
    t.column "manager_id",    :integer
    t.column "owner_id",      :integer
    t.column "priority_id",   :integer
  end

  add_index "apps", ["name"], :name => "index_apps_on_name"
  add_index "apps", ["department_id"], :name => "index_apps_on_department_id"
  add_index "apps", ["manager_id"], :name => "index_apps_on_manager_id"
  add_index "apps", ["owner_id"], :name => "index_apps_on_owner_id"

  create_table "architectures", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
    t.column "parent_id",   :integer
  end

  add_index "architectures", ["parent_id"], :name => "index_architectures_on_parent_id"
  add_index "architectures", ["name"], :name => "index_architectures_on_name"

  create_table "attachments", :force => true do |t|
    t.column "filename",        :string
    t.column "attachable_id",   :integer
    t.column "attachable_type", :string
    t.column "content_type",    :string
    t.column "data",            :binary
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "description",     :string
  end

  add_index "attachments", ["attachable_id"], :name => "index_attachments_on_attachable_id"
  add_index "attachments", ["attachable_type"], :name => "index_attachments_on_attachable_type"

  create_table "audits", :force => true do |t|
    t.column "auditable_id",   :integer
    t.column "auditable_type", :string
    t.column "user_id",        :integer
    t.column "user_type",      :string
    t.column "username",       :string
    t.column "action",         :string
    t.column "changes",        :text
    t.column "version",        :integer,  :default => 0
    t.column "created_at",     :datetime
  end

  add_index "audits", ["auditable_id", "auditable_type"], :name => "auditable_index"
  add_index "audits", ["user_id", "user_type"], :name => "user_index"
  add_index "audits", ["created_at"], :name => "index_audits_on_created_at"

  create_table "circuit_types", :force => true do |t|
    t.column "name",               :string
    t.column "flag",               :string
    t.column "description",        :text
    t.column "old_application_id", :integer
  end

  add_index "circuit_types", ["name"], :name => "index_circuit_types_on_name"

  create_table "circuits", :force => true do |t|
    t.column "parent_id",         :integer
    t.column "next_id",           :integer
    t.column "provider_id",       :integer
    t.column "line_speed_id",     :integer
    t.column "circuit_number",    :string
    t.column "description",       :text
    t.column "date_installed",    :date
    t.column "is_disconnected",   :boolean
    t.column "date_disconnected", :date
    t.column "circuit_type_id",   :integer
    t.column "line_type_id",      :integer
    t.column "old_circuit_id",    :integer
  end

  add_index "circuits", ["parent_id"], :name => "index_circuits_on_parent_id"
  add_index "circuits", ["next_id"], :name => "index_circuits_on_next_id"
  add_index "circuits", ["provider_id"], :name => "index_circuits_on_provider_id"
  add_index "circuits", ["line_speed_id"], :name => "index_circuits_on_line_speed_id"
  add_index "circuits", ["circuit_number"], :name => "index_circuits_on_circuit_number"
  add_index "circuits", ["is_disconnected"], :name => "index_circuits_on_is_disconnected"
  add_index "circuits", ["circuit_type_id"], :name => "index_circuits_on_circuit_type_id"
  add_index "circuits", ["line_type_id"], :name => "index_circuits_on_line_type_id"

  create_table "circuits_locations", :id => false, :force => true do |t|
    t.column "location_id", :integer
    t.column "circuit_id",  :integer
  end

  add_index "circuits_locations", ["location_id"], :name => "index_circuits_locations_on_location_id"
  add_index "circuits_locations", ["circuit_id"], :name => "index_circuits_locations_on_circuit_id"

  create_table "cities", :force => true do |t|
    t.column "name",     :string
    t.column "state_id", :integer
    t.column "po_city",  :string
    t.column "po_zip",   :string
  end

  add_index "cities", ["name"], :name => "index_cities_on_name"
  add_index "cities", ["state_id"], :name => "index_cities_on_state_id"
  add_index "cities", ["po_zip"], :name => "index_cities_on_po_zip"

  create_table "companies", :force => true do |t|
    t.column "name",            :string
    t.column "is_vendor",       :boolean
    t.column "contact_id",      :integer
    t.column "is_provider",     :boolean
    t.column "is_manufacturer", :boolean
    t.column "url",             :string
    t.column "bpo",             :string
    t.column "bpo_expiry",      :date
  end

  add_index "companies", ["is_vendor"], :name => "index_companies_on_is_vendor"
  add_index "companies", ["is_provider"], :name => "index_companies_on_is_provider"
  add_index "companies", ["contact_id"], :name => "index_companies_on_contact_id"
  add_index "companies", ["is_manufacturer"], :name => "index_companies_on_is_manufacturer"
  add_index "companies", ["name"], :name => "index_companies_on_name"

  create_table "components", :force => true do |t|
    t.column "parent_id", :integer
    t.column "is_base",   :boolean
  end

  add_index "components", ["parent_id"], :name => "index_components_on_parent_id"

  create_table "contacts", :force => true do |t|
    t.column "last_name",           :string
    t.column "first_name",          :string
    t.column "department_id",       :integer
    t.column "location_id",         :integer
    t.column "employee_number",     :string
    t.column "email",               :string
    t.column "manager_id",          :integer
    t.column "description",         :text
    t.column "employer_id",         :integer
    t.column "title",               :string
    t.column "is_purchase_contact", :boolean
    t.column "fund_code",           :integer
    t.column "management_center",   :integer
    t.column "work_order",          :string
    t.column "budget_code",         :integer
    t.column "is_manager",          :boolean
    t.column "is_engineer",         :boolean
  end

  add_index "contacts", ["employee_number"], :name => "index_contacts_on_employee_number", :unique => true
  add_index "contacts", ["last_name", "first_name"], :name => "full_name_index"
  add_index "contacts", ["department_id"], :name => "index_contacts_on_department_id"
  add_index "contacts", ["location_id"], :name => "index_contacts_on_location_id"
  add_index "contacts", ["manager_id"], :name => "index_contacts_on_manager_id"
  add_index "contacts", ["employer_id"], :name => "index_contacts_on_employer_id"
  add_index "contacts", ["is_purchase_contact"], :name => "index_contacts_on_is_purchase_contact"
  add_index "contacts", ["is_manager"], :name => "index_contacts_on_is_manager"
  add_index "contacts", ["is_engineer"], :name => "index_contacts_on_is_engineer"

  create_table "departments", :force => true do |t|
    t.column "name",           :string
    t.column "description",    :text
    t.column "alternate_name", :string
    t.column "parent_id",      :integer
    t.column "company_id",     :integer
  end

  add_index "departments", ["parent_id"], :name => "index_departments_on_parent_id"
  add_index "departments", ["name"], :name => "index_departments_on_name"
  add_index "departments", ["company_id"], :name => "index_departments_on_company_id"

  create_table "device_classes", :force => true do |t|
    t.column "parent_id",        :integer
    t.column "name",             :string
    t.column "description",      :text
    t.column "old_hostclass_id", :integer
    t.column "set_type",         :string
  end

  add_index "device_classes", ["parent_id"], :name => "index_device_classes_on_parent_id"
  add_index "device_classes", ["name"], :name => "index_device_classes_on_name"

  create_table "devices", :force => true do |t|
    t.column "device_class_id",      :integer
    t.column "equipment_id",         :integer
    t.column "contact_id",           :integer
    t.column "hostname",             :string
    t.column "description",          :text
    t.column "is_virtual",           :boolean
    t.column "is_dummy",             :boolean
    t.column "domain_id",            :integer
    t.column "primary_interface_id", :integer
    t.column "device_id",            :integer
    t.column "type",                 :string
    t.column "primary_engineer_id",  :integer
    t.column "is_san_connected",     :boolean
    t.column "is_tivoli_agent",      :boolean
    t.column "operating_system_id",  :integer
  end

  add_index "devices", ["device_class_id"], :name => "index_devices_on_device_class_id"
  add_index "devices", ["equipment_id"], :name => "index_devices_on_equipment_id"
  add_index "devices", ["contact_id"], :name => "index_devices_on_contact_id"
  add_index "devices", ["is_virtual"], :name => "index_devices_on_is_virtual"
  add_index "devices", ["is_dummy"], :name => "index_devices_on_is_dummy"
  add_index "devices", ["domain_id"], :name => "index_devices_on_domain_id"
  add_index "devices", ["primary_interface_id"], :name => "index_devices_on_primary_interface_id"
  add_index "devices", ["hostname"], :name => "index_devices_on_hostname"
  add_index "devices", ["device_id"], :name => "index_devices_on_device_id"
  add_index "devices", ["primary_engineer_id"], :name => "index_devices_on_primary_engineer_id"
  add_index "devices", ["operating_system_id"], :name => "index_devices_on_operating_system_id"
  add_index "devices", ["is_san_connected"], :name => "index_devices_on_is_san_connected"
  add_index "devices", ["is_tivoli_agent"], :name => "index_devices_on_is_tivoli_agent"

  create_table "dial_lines", :force => true do |t|
    t.column "device_id",   :integer
    t.column "circuit_id",  :integer
    t.column "description", :text
  end

  add_index "dial_lines", ["device_id"], :name => "index_dial_lines_on_device_id"
  add_index "dial_lines", ["circuit_id"], :name => "index_dial_lines_on_circuit_id"

  create_table "distributed_items", :force => true do |t|
    t.column "distributed_on", :date
    t.column "contact_id",     :integer
    t.column "order_item_id",  :integer
    t.column "quantity",       :integer
    t.column "processor_id",   :integer
  end

  add_index "distributed_items", ["contact_id"], :name => "index_distributed_items_on_contact_id"
  add_index "distributed_items", ["order_item_id"], :name => "index_distributed_items_on_order_item_id"
  add_index "distributed_items", ["distributed_on"], :name => "index_distributed_items_on_distributed_on"
  add_index "distributed_items", ["processor_id"], :name => "index_distributed_items_on_processor_id"

  create_table "domain_names", :force => true do |t|
    t.column "nameable_id",     :integer
    t.column "nameable_type",   :string
    t.column "hostname",        :string
    t.column "domain_id",       :integer
    t.column "publish_reverse", :boolean
    t.column "created_on",      :date
    t.column "updated_on",      :date
  end

  add_index "domain_names", ["nameable_id"], :name => "index_domain_names_on_nameable_id"
  add_index "domain_names", ["nameable_type"], :name => "index_domain_names_on_nameable_type"
  add_index "domain_names", ["domain_id"], :name => "index_domain_names_on_domain_id"
  add_index "domain_names", ["hostname"], :name => "index_domain_names_on_hostname"

  create_table "domains", :force => true do |t|
    t.column "parent_id",         :integer
    t.column "name",              :string
    t.column "description",       :text
    t.column "autodns",           :boolean
    t.column "maintainer_id",     :integer
    t.column "primary_server_id", :integer
    t.column "generate_soa",      :boolean
    t.column "soa_timer_section", :string
  end

  add_index "domains", ["parent_id"], :name => "index_domains_on_parent_id"
  add_index "domains", ["name"], :name => "index_domains_on_name"
  add_index "domains", ["autodns"], :name => "index_domains_on_autodns"
  add_index "domains", ["maintainer_id"], :name => "index_domains_on_maintainer_id"
  add_index "domains", ["primary_server_id"], :name => "index_domains_on_primary_server_id"

  create_table "domains_servers", :id => false, :force => true do |t|
    t.column "domain_id", :integer
    t.column "server_id", :integer
  end

  add_index "domains_servers", ["domain_id"], :name => "index_domains_servers_on_domain_id"
  add_index "domains_servers", ["server_id"], :name => "index_domains_servers_on_server_id"

  create_table "engineers_projects", :id => false, :force => true do |t|
    t.column "engineer_id", :integer
    t.column "project_id",  :integer
  end

  add_index "engineers_projects", ["engineer_id"], :name => "index_engineers_projects_on_engineer_id"
  add_index "engineers_projects", ["project_id"], :name => "index_engineers_projects_on_project_id"

  create_table "equipment", :force => true do |t|
    t.column "product_id",          :integer
    t.column "parent_id",           :integer
    t.column "delivery_date",       :date
    t.column "location_id",         :integer
    t.column "tag_number",          :string
    t.column "serial_number",       :string
    t.column "host_identifier",     :string
    t.column "status_id",           :integer
    t.column "count",               :integer
    t.column "equipment_status_id", :integer
    t.column "warranty_expiry",     :date
    t.column "role_id",             :integer
  end

  add_index "equipment", ["product_id"], :name => "index_equipment_on_product_id"
  add_index "equipment", ["parent_id"], :name => "index_equipment_on_parent_id"
  add_index "equipment", ["location_id"], :name => "index_equipment_on_location_id"
  add_index "equipment", ["status_id"], :name => "index_equipment_on_status_id"
  add_index "equipment", ["count"], :name => "index_equipment_on_count"
  add_index "equipment", ["serial_number"], :name => "index_equipment_on_serial_number"
  add_index "equipment", ["equipment_status_id"], :name => "index_equipment_on_equipment_status_id"
  add_index "equipment", ["role_id"], :name => "index_equipment_on_role_id"

  create_table "equipment_properties", :force => true do |t|
    t.column "equipment_id", :integer
    t.column "property_id",  :integer
    t.column "value",        :string
  end

  add_index "equipment_properties", ["equipment_id"], :name => "index_equipment_properties_on_equipment_id"
  add_index "equipment_properties", ["property_id"], :name => "index_equipment_properties_on_property_id"

  create_table "equipment_statuses", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
    t.column "flag",        :string
  end

  add_index "equipment_statuses", ["name"], :name => "index_equipment_statuses_on_name"

  create_table "interfaces", :force => true do |t|
    t.column "device_id",        :integer
    t.column "hardware_address", :string
    t.column "name",             :string
    t.column "is_dynamic",       :boolean
    t.column "topology_id",      :integer
    t.column "vlanid",           :integer
    t.column "is_wireless",      :boolean
  end

  add_index "interfaces", ["device_id"], :name => "index_interfaces_on_device_id"
  add_index "interfaces", ["hardware_address"], :name => "index_interfaces_on_hardware_address"
  add_index "interfaces", ["topology_id"], :name => "index_interfaces_on_topology_id"
  add_index "interfaces", ["is_wireless"], :name => "index_interfaces_on_is_wireless"

  create_table "ipv4_address_holds", :force => true do |t|
    t.column "ipv4_subnet_id",    :integer
    t.column "ip_address_packed", :integer,  :limit => 8
    t.column "held_on",           :datetime
  end

  add_index "ipv4_address_holds", ["ipv4_subnet_id"], :name => "index_ipv4_address_holds_on_ipv4_subnet_id"
  add_index "ipv4_address_holds", ["ip_address_packed"], :name => "index_ipv4_address_holds_on_ip_address_packed"
  add_index "ipv4_address_holds", ["held_on"], :name => "index_ipv4_address_holds_on_held_on"

  create_table "ipv4_address_ranges", :force => true do |t|
    t.column "zone_id",              :integer
    t.column "ipv4_scope_id",        :integer
    t.column "is_dynamic",           :boolean
    t.column "is_reserved",          :boolean
    t.column "start_address",        :string
    t.column "start_address_packed", :integer, :limit => 8
    t.column "end_address",          :string
    t.column "end_address_packed",   :integer, :limit => 8
  end

  add_index "ipv4_address_ranges", ["zone_id"], :name => "index_ipv4_address_ranges_on_zone_id"
  add_index "ipv4_address_ranges", ["ipv4_scope_id"], :name => "index_ipv4_address_ranges_on_ipv4_scope_id"

  create_table "ipv4_assigned_networks", :force => true do |t|
    t.column "subnet_address",        :string
    t.column "subnet_address_packed", :integer, :limit => 8
    t.column "prefix",                :integer
    t.column "description",           :text
  end

  create_table "ipv4_assignments", :force => true do |t|
    t.column "zone_id",               :integer
    t.column "prefix",                :integer
    t.column "network_class_id",      :integer
    t.column "topology_id",           :integer
    t.column "assign_prefix",         :integer
    t.column "description",           :text
    t.column "subnet_address",        :string
    t.column "subnet_address_packed", :integer, :limit => 8
  end

  add_index "ipv4_assignments", ["zone_id"], :name => "index_ipv4_assignments_on_zone_id"
  add_index "ipv4_assignments", ["network_class_id"], :name => "index_ipv4_assignments_on_network_class_id"
  add_index "ipv4_assignments", ["topology_id"], :name => "index_ipv4_assignments_on_topology_id"

  create_table "ipv4_interfaces", :force => true do |t|
    t.column "ipv4_subnet_id",    :integer
    t.column "interface_id",      :integer
    t.column "is_reserved",       :boolean
    t.column "is_delinquent",     :boolean
    t.column "is_stealth",        :boolean
    t.column "is_rogue",          :boolean
    t.column "is_virtual",        :boolean
    t.column "ip_address",        :string
    t.column "ip_address_packed", :integer,  :limit => 8
    t.column "old_interface_id",  :integer
    t.column "created_on",        :datetime
    t.column "updated_on",        :datetime
    t.column "ping_count",        :integer
    t.column "last_pinged_on",    :datetime
  end

  add_index "ipv4_interfaces", ["ipv4_subnet_id"], :name => "index_ipv4_interfaces_on_ipv4_subnet_id"
  add_index "ipv4_interfaces", ["interface_id"], :name => "index_ipv4_interfaces_on_interface_id"
  add_index "ipv4_interfaces", ["ip_address_packed"], :name => "index_ipv4_interfaces_on_ip_address_packed"

  create_table "ipv4_networks", :force => true do |t|
    t.column "network_address", :integer
    t.column "network_mask",    :integer
    t.column "description",     :text
  end

  create_table "ipv4_schema_rules", :force => true do |t|
    t.column "zone_id",                :integer
    t.column "network_address_packed", :integer, :limit => 8
    t.column "network_mask_packed",    :integer, :limit => 8
    t.column "device_class_id",        :integer
    t.column "lbound",                 :integer
    t.column "ubound",                 :integer
    t.column "description",            :text
    t.column "network_address",        :string
    t.column "network_mask",           :string
  end

  add_index "ipv4_schema_rules", ["zone_id"], :name => "index_ipv4_schema_rules_on_zone_id"
  add_index "ipv4_schema_rules", ["device_class_id"], :name => "index_ipv4_schema_rules_on_device_class_id"

  create_table "ipv4_scope_option_entries", :force => true do |t|
    t.column "ipv4_scope_id",        :integer
    t.column "ipv4_scope_option_id", :integer
    t.column "value",                :string
  end

  create_table "ipv4_scope_options", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
    t.column "value",       :string
  end

  create_table "ipv4_scopes", :force => true do |t|
    t.column "ipv4_subnet_id", :integer
    t.column "name",           :string
    t.column "description",    :text
    t.column "server_id",      :integer
    t.column "gateway_id",     :integer
  end

  add_index "ipv4_scopes", ["ipv4_subnet_id"], :name => "index_ipv4_scopes_on_ipv4_subnet_id"
  add_index "ipv4_scopes", ["server_id"], :name => "index_ipv4_scopes_on_server_id"
  add_index "ipv4_scopes", ["gateway_id"], :name => "index_ipv4_scopes_on_gateway_id"

  create_table "ipv4_subnets", :force => true do |t|
    t.column "subnet_id",             :integer
    t.column "parent_id",             :integer
    t.column "zone_id",               :integer
    t.column "subnet_address",        :string
    t.column "subnet_address_packed", :integer, :limit => 8
    t.column "subnet_mask",           :string
    t.column "subnet_mask_packed",    :integer, :limit => 8
    t.column "description",           :text
    t.column "old_network_id",        :integer
    t.column "gateway_address",       :string
  end

  add_index "ipv4_subnets", ["zone_id"], :name => "index_ipv4_subnets_on_zone_id"
  add_index "ipv4_subnets", ["parent_id"], :name => "index_ipv4_subnets_on_parent_id"
  add_index "ipv4_subnets", ["subnet_id"], :name => "index_ipv4_subnets_on_subnet_id"
  add_index "ipv4_subnets", ["subnet_address_packed"], :name => "index_ipv4_subnets_on_subnet_address_packed"
  add_index "ipv4_subnets", ["subnet_mask_packed"], :name => "index_ipv4_subnets_on_subnet_mask_packed"

  create_table "ipv4_virtual_host_interfaces", :force => true do |t|
    t.column "ipv4_virtual_host_id", :integer
    t.column "ipv4_interface_id",    :integer
    t.column "priority",             :integer
  end

  add_index "ipv4_virtual_host_interfaces", ["ipv4_virtual_host_id"], :name => "index_ipv4_virtual_host_interfaces_on_ipv4_virtual_host_id"
  add_index "ipv4_virtual_host_interfaces", ["ipv4_interface_id"], :name => "index_ipv4_virtual_host_interfaces_on_ipv4_interface_id"

  create_table "ipv4_virtual_hosts", :force => true do |t|
    t.column "ipv4_subnet_id",       :integer
    t.column "vrid",                 :integer
    t.column "description",          :text
    t.column "ipv4_interface_id",    :integer
    t.column "is_vrrp",              :boolean
    t.column "old_virtual_id",       :integer
    t.column "virtual_host_type_id", :integer
    t.column "otherid",              :integer
  end

  add_index "ipv4_virtual_hosts", ["ipv4_subnet_id"], :name => "index_ipv4_virtual_hosts_on_ipv4_subnet_id"
  add_index "ipv4_virtual_hosts", ["ipv4_interface_id"], :name => "index_ipv4_virtual_hosts_on_ipv4_interface_id"
  add_index "ipv4_virtual_hosts", ["virtual_host_type_id"], :name => "index_ipv4_virtual_hosts_on_virtual_host_type_id"

  create_table "line_speeds", :force => true do |t|
    t.column "topology_id",      :integer
    t.column "parent_id",        :integer
    t.column "name",             :string
    t.column "speed",            :string
    t.column "old_linespeed_id", :integer
  end

  add_index "line_speeds", ["topology_id"], :name => "index_line_speeds_on_topology_id"
  add_index "line_speeds", ["parent_id"], :name => "index_line_speeds_on_parent_id"
  add_index "line_speeds", ["name"], :name => "index_line_speeds_on_name"

  create_table "line_types", :force => true do |t|
    t.column "name",           :string
    t.column "description",    :text
    t.column "parent_id",      :integer
    t.column "old_channel_id", :integer
  end

  add_index "line_types", ["parent_id"], :name => "index_line_types_on_parent_id"
  add_index "line_types", ["name"], :name => "index_line_types_on_name"

  create_table "link_categories", :force => true do |t|
    t.column "parent_id",   :integer
    t.column "name",        :string
    t.column "description", :text
  end

  add_index "link_categories", ["parent_id"], :name => "index_link_categories_on_parent_id"
  add_index "link_categories", ["name"], :name => "index_link_categories_on_name"

  create_table "links", :force => true do |t|
    t.column "linkable_id",      :integer
    t.column "linkable_type",    :string
    t.column "link_category_id", :integer
    t.column "url",              :string
    t.column "title",            :string
  end

  add_index "links", ["linkable_id"], :name => "index_links_on_linkable_id"
  add_index "links", ["linkable_type"], :name => "index_links_on_linkable_type"
  add_index "links", ["link_category_id"], :name => "index_links_on_link_category_id"

  create_table "locations", :force => true do |t|
    t.column "parent_id",            :integer
    t.column "name",                 :string
    t.column "depth",                :integer
    t.column "description",          :text
    t.column "contact_id",           :integer
    t.column "nick_name",            :string
    t.column "short_name",           :string
    t.column "mailstop",             :string
    t.column "latitude",             :decimal, :precision => 15, :scale => 10
    t.column "longitude",            :decimal, :precision => 15, :scale => 10
    t.column "is_delivery_location", :boolean
    t.column "old_id",               :integer
    t.column "long_name",            :string
    t.column "is_storage_location",  :boolean
    t.column "is_data_center",       :boolean
  end

  add_index "locations", ["parent_id"], :name => "index_locations_on_parent_id"
  add_index "locations", ["name"], :name => "index_locations_on_name"
  add_index "locations", ["contact_id"], :name => "index_locations_on_contact_id"
  add_index "locations", ["long_name"], :name => "index_locations_on_long_name"
  add_index "locations", ["depth"], :name => "index_locations_on_depth"
  add_index "locations", ["is_delivery_location"], :name => "index_locations_on_is_delivery_location"
  add_index "locations", ["is_storage_location"], :name => "index_locations_on_is_storage_location"
  add_index "locations", ["is_data_center"], :name => "index_locations_on_is_data_center"

  create_table "maintenance_logs", :force => true do |t|
    t.column "loggable_id",   :integer
    t.column "loggable_type", :string
    t.column "created_on",    :datetime
    t.column "updated_on",    :datetime
    t.column "created_by",    :string
    t.column "title",         :string
    t.column "body",          :text
  end

  add_index "maintenance_logs", ["loggable_id"], :name => "index_maintenance_logs_on_loggable_id"
  add_index "maintenance_logs", ["loggable_type"], :name => "index_maintenance_logs_on_loggable_type"
  add_index "maintenance_logs", ["created_on"], :name => "index_maintenance_logs_on_created_on"

  create_table "mp_dlcis", :force => true do |t|
    t.column "dlci",         :integer
    t.column "mp_line_id",   :integer
    t.column "interface_id", :integer
    t.column "old_dlci_id",  :integer
  end

  add_index "mp_dlcis", ["mp_line_id"], :name => "index_mp_dlcis_on_mp_line_id"
  add_index "mp_dlcis", ["interface_id"], :name => "index_mp_dlcis_on_interface_id"

  create_table "mp_lines", :force => true do |t|
    t.column "device_id",      :integer
    t.column "circuit_id",     :integer
    t.column "old_mp_line_id", :integer
  end

  add_index "mp_lines", ["device_id"], :name => "index_mp_lines_on_device_id"
  add_index "mp_lines", ["circuit_id"], :name => "index_mp_lines_on_circuit_id"

  create_table "mp_pvcs", :force => true do |t|
    t.column "dlci_a_id",  :integer
    t.column "dlci_b_id",  :integer
    t.column "old_pvc_id", :integer
  end

  add_index "mp_pvcs", ["dlci_a_id"], :name => "index_mp_pvcs_on_dlci_a_id"
  add_index "mp_pvcs", ["dlci_b_id"], :name => "index_mp_pvcs_on_dlci_b_id"

  create_table "network_classes", :force => true do |t|
    t.column "parent_id",       :integer
    t.column "name",            :string
    t.column "description",     :text
    t.column "old_netclass_id", :integer
  end

  add_index "network_classes", ["parent_id"], :name => "index_network_classes_on_parent_id"
  add_index "network_classes", ["name"], :name => "index_network_classes_on_name"

  create_table "notes", :force => true do |t|
    t.column "body",         :text
    t.column "notable_id",   :integer
    t.column "notable_type", :string
    t.column "created_on",   :datetime
    t.column "updated_on",   :datetime
    t.column "created_by",   :string
  end

  add_index "notes", ["notable_id", "notable_type"], :name => "notable_index"

  create_table "operating_systems", :force => true do |t|
    t.column "parent_id",   :integer
    t.column "name",        :string
    t.column "long_name",   :string
    t.column "description", :text
  end

  add_index "operating_systems", ["parent_id"], :name => "index_operating_systems_on_parent_id"
  add_index "operating_systems", ["name"], :name => "index_operating_systems_on_name"

  create_table "order_items", :force => true do |t|
    t.column "product_id",     :integer
    t.column "quantity",       :integer
    t.column "unit_price",     :decimal, :precision => 10, :scale => 2
    t.column "can_substitute", :boolean
    t.column "order_id",       :integer
    t.column "details",        :text
  end

  add_index "order_items", ["product_id"], :name => "index_order_items_on_product_id"
  add_index "order_items", ["quantity"], :name => "index_order_items_on_quantity"
  add_index "order_items", ["order_id"], :name => "index_order_items_on_order_id"

  create_table "order_statuses", :force => true do |t|
    t.column "name",  :string
    t.column "value", :integer
  end

  add_index "order_statuses", ["name"], :name => "index_order_statuses_on_name"

  create_table "order_types", :force => true do |t|
    t.column "name",         :string
    t.column "processor_id", :integer
  end

  add_index "order_types", ["name"], :name => "index_order_types_on_name"
  add_index "order_types", ["processor_id"], :name => "index_order_types_on_processor_id"

  create_table "orders", :force => true do |t|
    t.column "order_number",              :integer
    t.column "ordered_on",                :date
    t.column "description",               :text
    t.column "priority",                  :integer
    t.column "order_status_old",          :integer
    t.column "requestor_id",              :integer
    t.column "is_approved",               :boolean
    t.column "approved_by",               :string
    t.column "approved_on",               :date
    t.column "order_type_old",            :integer
    t.column "other_order_number",        :string
    t.column "justification",             :text
    t.column "department_id",             :integer
    t.column "assignee",                  :text
    t.column "related_pc01",              :string
    t.column "department_control_number", :string
    t.column "old_project",               :string
    t.column "hwdl",                      :string
    t.column "hw",                        :string
    t.column "order_type_id",             :integer
    t.column "manager_id",                :integer
    t.column "project_id",                :integer
    t.column "service_request",           :string
    t.column "management_center",         :string
    t.column "pc01_id",                   :integer
    t.column "closed_on",                 :date
    t.column "order_status_id",           :integer
    t.column "budget_year",               :integer
    t.column "fund_code",                 :integer
    t.column "work_order",                :string
    t.column "budget_code",               :integer
  end

  add_index "orders", ["order_number"], :name => "index_orders_on_order_number"
  add_index "orders", ["ordered_on"], :name => "index_orders_on_ordered_on"
  add_index "orders", ["requestor_id"], :name => "index_orders_on_requestor_id"
  add_index "orders", ["is_approved"], :name => "index_orders_on_is_approved"
  add_index "orders", ["department_id"], :name => "index_orders_on_department_id"
  add_index "orders", ["order_type_id"], :name => "index_orders_on_order_type_id"
  add_index "orders", ["manager_id"], :name => "index_orders_on_manager_id"
  add_index "orders", ["project_id"], :name => "index_orders_on_project_id"
  add_index "orders", ["pc01_id"], :name => "index_orders_on_pc01_id"
  add_index "orders", ["closed_on"], :name => "index_orders_on_closed_on"
  add_index "orders", ["order_status_id"], :name => "index_orders_on_order_status_id"

  create_table "pc01_categories", :force => true do |t|
    t.column "title",         :string
    t.column "description",   :text
    t.column "order_type_id", :integer
  end

  add_index "pc01_categories", ["title"], :name => "index_pc01_categories_on_title"

  create_table "pc01_items", :force => true do |t|
    t.column "pc01_id",            :integer
    t.column "pc01_category_id",   :integer
    t.column "description",        :text
    t.column "is_stock_item",      :boolean
    t.column "is_fullfilled",      :boolean
    t.column "is_replenished",     :boolean
    t.column "quantity",           :integer
    t.column "is_charge_back",     :boolean
    t.column "replenished_on",     :date
    t.column "charge_back_amount", :decimal, :precision => 10, :scale => 2
    t.column "is_true_up",         :boolean
  end

  add_index "pc01_items", ["pc01_id"], :name => "index_pc01_items_on_pc01_id"
  add_index "pc01_items", ["pc01_category_id"], :name => "index_pc01_items_on_pc01_category_id"
  add_index "pc01_items", ["is_stock_item"], :name => "index_pc01_items_on_is_stock_item"
  add_index "pc01_items", ["is_fullfilled"], :name => "index_pc01_items_on_is_fullfilled"
  add_index "pc01_items", ["is_replenished"], :name => "index_pc01_items_on_is_replenished"
  add_index "pc01_items", ["is_charge_back"], :name => "index_pc01_items_on_is_charge_back"
  add_index "pc01_items", ["is_true_up"], :name => "index_pc01_items_on_is_true_up"

  create_table "pc01s", :force => true do |t|
    t.column "pc01_number",       :integer
    t.column "pc01_dated",        :date
    t.column "received_on",       :date
    t.column "approved_on",       :date
    t.column "approved_by",       :integer
    t.column "service_request",   :string
    t.column "submitted_by",      :integer
    t.column "location_id",       :integer
    t.column "description",       :text
    t.column "management_center", :string
    t.column "is_completed",      :boolean
    t.column "created_on",        :datetime
    t.column "department_id",     :integer
    t.column "assigned_users",    :text
    t.column "budget_year",       :integer
    t.column "fund_code",         :integer
    t.column "work_order",        :string
    t.column "budget_code",       :integer
  end

  add_index "pc01s", ["pc01_number"], :name => "index_pc01s_on_pc01_number"
  add_index "pc01s", ["received_on"], :name => "index_pc01s_on_received_on"
  add_index "pc01s", ["approved_on"], :name => "index_pc01s_on_approved_on"
  add_index "pc01s", ["submitted_by"], :name => "index_pc01s_on_submitted_by"
  add_index "pc01s", ["location_id"], :name => "index_pc01s_on_location_id"
  add_index "pc01s", ["department_id"], :name => "index_pc01s_on_department_id"

  create_table "phone_types", :force => true do |t|
    t.column "phone_type", :string
  end

  add_index "phone_types", ["phone_type"], :name => "index_phone_types_on_phone_type"

  create_table "phones", :force => true do |t|
    t.column "number",        :string
    t.column "phone_type_id", :integer
    t.column "phonable_id",   :integer
    t.column "phonable_type", :string
    t.column "description",   :text
  end

  add_index "phones", ["phone_type_id"], :name => "index_phones_on_phone_type_id"
  add_index "phones", ["phonable_id", "phonable_type"], :name => "phonable_index"

  create_table "pp_lines", :force => true do |t|
    t.column "circuit_id",    :integer
    t.column "subnet_id",     :integer
    t.column "map_reference", :integer
  end

  add_index "pp_lines", ["circuit_id"], :name => "index_pp_lines_on_circuit_id"
  add_index "pp_lines", ["subnet_id"], :name => "index_pp_lines_on_subnet_id"
  add_index "pp_lines", ["map_reference"], :name => "index_pp_lines_on_map_reference"

  create_table "print_daemon_types", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
  end

  create_table "print_daemons", :force => true do |t|
    t.column "print_daemon_type_id", :integer
    t.column "server_id",            :integer
    t.column "printer_id",           :integer
    t.column "name",                 :string
  end

  create_table "priorities", :force => true do |t|
    t.column "name",  :string
    t.column "value", :integer
  end

  add_index "priorities", ["name"], :name => "index_priorities_on_name"

  create_table "product_families", :force => true do |t|
    t.column "manufacturer_id", :integer
    t.column "name",            :string
    t.column "alias",           :string
  end

  add_index "product_families", ["manufacturer_id"], :name => "index_product_families_on_vendor_id"
  add_index "product_families", ["name"], :name => "index_product_families_on_name"

  create_table "product_properties", :force => true do |t|
    t.column "product_id",  :integer
    t.column "property_id", :integer
  end

  add_index "product_properties", ["product_id"], :name => "index_product_properties_on_product_id"
  add_index "product_properties", ["property_id"], :name => "index_product_properties_on_property_id"

  create_table "products", :force => true do |t|
    t.column "device_class_id",   :integer
    t.column "architecture_id",   :integer
    t.column "model_number",      :string
    t.column "part_number",       :string
    t.column "spare_number",      :string
    t.column "description",       :text
    t.column "detailed",          :boolean
    t.column "name",              :string
    t.column "product_family_id", :integer
    t.column "full_name",         :text
    t.column "power_consumption", :integer
    t.column "heat_output",       :integer
  end

  add_index "products", ["device_class_id"], :name => "index_products_on_device_class_id"
  add_index "products", ["architecture_id"], :name => "index_products_on_architecture_id"
  add_index "products", ["product_family_id"], :name => "index_products_on_product_family_id"
  add_index "products", ["name"], :name => "index_products_on_name"
  add_index "products", ["detailed"], :name => "index_products_on_detailed"
  add_index "products", ["model_number"], :name => "index_products_on_model_number"
  add_index "products", ["part_number"], :name => "index_products_on_part_number"

  create_table "project_statuses", :force => true do |t|
    t.column "name",  :string
    t.column "value", :integer
  end

  add_index "project_statuses", ["name"], :name => "index_project_statuses_on_name"

  create_table "project_types", :force => true do |t|
    t.column "name",         :string
    t.column "description",  :string
    t.column "abbreviation", :string
  end

  add_index "project_types", ["name"], :name => "index_project_types_on_name"
  add_index "project_types", ["abbreviation"], :name => "index_project_types_on_abbreviation"

  create_table "project_updates", :force => true do |t|
    t.column "project_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
    t.column "created_by", :string
    t.column "body",       :text
  end

  create_table "projects", :force => true do |t|
    t.column "title",                :string
    t.column "description",          :text
    t.column "comments",             :text
    t.column "created_by",           :string
    t.column "created_on",           :datetime
    t.column "updated_on",           :datetime
    t.column "project_number",       :integer
    t.column "project_status",       :integer
    t.column "manager_id",           :integer
    t.column "department_id",        :integer
    t.column "requestor_id",         :integer
    t.column "priority",             :integer
    t.column "started_on",           :date
    t.column "completed_on",         :date
    t.column "estimated_completion", :string
    t.column "lead_engineer_id",     :integer
    t.column "project_type_id",      :integer
    t.column "project_status_id",    :integer
    t.column "priority_id",          :integer
    t.column "requested_on",         :date
    t.column "old_project_number",   :string
    t.column "service_request",      :string
  end

  add_index "projects", ["title"], :name => "index_projects_on_title"
  add_index "projects", ["manager_id"], :name => "index_projects_on_manager_id"
  add_index "projects", ["department_id"], :name => "index_projects_on_department_id"
  add_index "projects", ["requestor_id"], :name => "index_projects_on_requestor_id"
  add_index "projects", ["priority"], :name => "index_projects_on_priority"
  add_index "projects", ["lead_engineer_id"], :name => "index_projects_on_engineer_id"
  add_index "projects", ["project_type_id"], :name => "index_projects_on_project_type_id"
  add_index "projects", ["project_status_id"], :name => "index_projects_on_project_status_id"
  add_index "projects", ["priority_id"], :name => "index_projects_on_priority_id"

  create_table "properties", :force => true do |t|
    t.column "name", :string
    t.column "unit", :string
  end

  add_index "properties", ["name"], :name => "index_properties_on_name"

  create_table "received_items", :force => true do |t|
    t.column "received_on",         :datetime
    t.column "receiver_id",         :integer
    t.column "requisition_item_id", :integer
    t.column "quantity",            :integer
  end

  add_index "received_items", ["received_on"], :name => "index_received_items_on_received_on"
  add_index "received_items", ["receiver_id"], :name => "index_received_items_on_receiver_id"
  add_index "received_items", ["requisition_item_id"], :name => "index_received_items_on_requisition_item_id"

  create_table "related_tasks", :force => true do |t|
    t.column "task_id",         :integer
    t.column "related_task_id", :integer
  end

  add_index "related_tasks", ["task_id"], :name => "index_related_tasks_on_task_id"
  add_index "related_tasks", ["related_task_id"], :name => "index_related_tasks_on_related_task_id"

  create_table "reports", :force => true do |t|
    t.column "title",       :string
    t.column "description", :text
    t.column "model",       :string
    t.column "filters",     :text
    t.column "action",      :string
    t.column "controller",  :string
  end

  add_index "reports", ["title"], :name => "index_reports_on_title"
  add_index "reports", ["action"], :name => "index_reports_on_action"
  add_index "reports", ["controller"], :name => "index_reports_on_controller"

  create_table "requisition_items", :force => true do |t|
    t.column "requisition_id", :integer
    t.column "order_item_id",  :integer
    t.column "quantity",       :integer
    t.column "unit_price",     :decimal, :precision => 10, :scale => 2
    t.column "details",        :text
  end

  add_index "requisition_items", ["requisition_id"], :name => "index_requisition_items_on_requisition_id"
  add_index "requisition_items", ["order_item_id"], :name => "index_requisition_items_on_order_item_id"
  add_index "requisition_items", ["quantity"], :name => "index_requisition_items_on_quantity"

  create_table "requisition_statuses", :force => true do |t|
    t.column "name",  :string
    t.column "value", :integer
  end

  add_index "requisition_statuses", ["name"], :name => "index_requisition_statuses_on_name"

  create_table "requisitions", :force => true do |t|
    t.column "requisitioned_on",       :date
    t.column "requisition_number",     :string
    t.column "purchase_order",         :string
    t.column "vendor_id",              :integer
    t.column "requisition_status_old", :integer
    t.column "processor_id",           :integer
    t.column "purchased_on",           :date
    t.column "created_on",             :date
    t.column "sent_emails",            :boolean
    t.column "awarded_on",             :date
    t.column "management_center",      :string
    t.column "budget_account",         :string
    t.column "price_quote_number",     :string
    t.column "due_by",                 :datetime
    t.column "deliver_by",             :date
    t.column "release_number",         :string
    t.column "comment",                :string
    t.column "is_pcard_purchase",      :boolean
    t.column "requisition_status_id",  :integer
  end

  add_index "requisitions", ["requisitioned_on"], :name => "index_requisitions_on_requisitioned_on"
  add_index "requisitions", ["requisition_number"], :name => "index_requisitions_on_requisition_number"
  add_index "requisitions", ["purchase_order"], :name => "index_requisitions_on_purchase_order"
  add_index "requisitions", ["vendor_id"], :name => "index_requisitions_on_vendor_id"
  add_index "requisitions", ["requisition_status_id"], :name => "index_requisitions_on_requisition_status_id"
  add_index "requisitions", ["processor_id"], :name => "index_requisitions_on_processor_id"
  add_index "requisitions", ["release_number"], :name => "index_requisitions_on_release_number"

  create_table "roles", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
    t.column "flag",        :string
  end

  add_index "roles", ["name"], :name => "index_roles_on_name"
  add_index "roles", ["flag"], :name => "index_roles_on_flag"

  create_table "roles_tasks", :id => false, :force => true do |t|
    t.column "role_id", :integer
    t.column "task_id", :integer
  end

  add_index "roles_tasks", ["role_id"], :name => "index_roles_tasks_on_role_id"
  add_index "roles_tasks", ["task_id"], :name => "index_roles_tasks_on_task_id"

  create_table "roles_users", :id => false, :force => true do |t|
    t.column "user_id", :integer
    t.column "role_id", :integer
  end

  add_index "roles_users", ["user_id"], :name => "index_roles_users_on_user_id"
  add_index "roles_users", ["role_id"], :name => "index_roles_users_on_role_id"

  create_table "service_statuses", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
    t.column "value",       :integer
  end

  add_index "service_statuses", ["name"], :name => "index_service_statuses_on_name"

  create_table "services", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
  end

  add_index "services", ["name"], :name => "index_services_on_name"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "states", :force => true do |t|
    t.column "name", :string
    t.column "abbr", :string
  end

  add_index "states", ["name"], :name => "index_states_on_name", :unique => true

  create_table "subnets", :force => true do |t|
    t.column "description",      :text
    t.column "date_installed",   :date
    t.column "network_class_id", :integer
    t.column "topology_id",      :integer
    t.column "is_delinquent",    :boolean
    t.column "is_stealth",       :boolean
    t.column "is_reserved",      :boolean
    t.column "vlanid",           :integer
    t.column "is_private",       :boolean
    t.column "is_local",         :boolean
    t.column "virtual_lan_id",   :integer
  end

  add_index "subnets", ["network_class_id"], :name => "index_subnets_on_network_class_id"
  add_index "subnets", ["topology_id"], :name => "index_subnets_on_topology_id"
  add_index "subnets", ["vlanid"], :name => "index_subnets_on_vlanid"
  add_index "subnets", ["virtual_lan_id"], :name => "index_subnets_on_virtual_lan_id"

  create_table "tasks", :force => true do |t|
    t.column "title",         :string
    t.column "description",   :text
    t.column "url",           :string
    t.column "task_group_id", :integer
    t.column "parent_id",     :integer
    t.column "action",        :string
    t.column "controller",    :string
    t.column "hidden",        :boolean
  end

  add_index "tasks", ["title"], :name => "index_tasks_on_title"
  add_index "tasks", ["parent_id"], :name => "index_tasks_on_parent_id"
  add_index "tasks", ["task_group_id"], :name => "index_tasks_on_task_group_id"
  add_index "tasks", ["action"], :name => "index_tasks_on_action"
  add_index "tasks", ["controller"], :name => "index_tasks_on_controller"

  create_table "topologies", :force => true do |t|
    t.column "parent_id",       :integer
    t.column "name",            :string
    t.column "description",     :text
    t.column "old_topology_id", :integer
  end

  add_index "topologies", ["parent_id"], :name => "index_topologies_on_parent_id"
  add_index "topologies", ["name"], :name => "index_topologies_on_name"

  create_table "users", :force => true do |t|
    t.column "username",           :string
    t.column "dn",                 :string
    t.column "contact_id",         :integer
    t.column "last_login",         :datetime
    t.column "default_action",     :string
    t.column "default_controller", :string
    t.column "logged_in",          :boolean
  end

  add_index "users", ["username"], :name => "index_users_on_username"
  add_index "users", ["contact_id"], :name => "index_users_on_contact_id"

  create_table "virtual_host_types", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
  end

  add_index "virtual_host_types", ["name"], :name => "index_virtual_host_types_on_name"

  create_table "virtual_lans", :force => true do |t|
    t.column "vlanid",      :integer
    t.column "name",        :string
    t.column "description", :text
    t.column "is_private",  :boolean
  end

  add_index "virtual_lans", ["vlanid"], :name => "index_virtual_lans_on_vlanid"
  add_index "virtual_lans", ["name"], :name => "index_virtual_lans_on_name"

  create_table "wireless_interfaces", :force => true do |t|
    t.column "contact_id",       :integer
    t.column "interface_id",     :integer
    t.column "is_enabled",       :boolean
    t.column "created_on",       :datetime
    t.column "updated_on",       :datetime
    t.column "description",      :text
    t.column "expires_on",       :date
    t.column "hardware_address", :string
  end

  add_index "wireless_interfaces", ["contact_id"], :name => "index_wireless_interfaces_on_contact_id"
  add_index "wireless_interfaces", ["interface_id"], :name => "index_wireless_interfaces_on_interface_id"
  add_index "wireless_interfaces", ["is_enabled"], :name => "index_wireless_interfaces_on_is_enabled"

  create_table "wireless_output_filters", :force => true do |t|
    t.column "title",         :text
    t.column "description",   :text
    t.column "is_active",     :boolean
    t.column "created_on",    :datetime
    t.column "updated_on",    :datetime
    t.column "output_filter", :text
  end

  add_index "wireless_output_filters", ["is_active"], :name => "index_wireless_output_filters_on_is_active"

  create_table "workstations", :force => true do |t|
    t.column "device_id",   :integer
    t.column "contact_id",  :integer
    t.column "description", :text
  end

  add_index "workstations", ["device_id"], :name => "index_workstations_on_device_id"
  add_index "workstations", ["contact_id"], :name => "index_workstations_on_contact_id"

  create_table "zones", :force => true do |t|
    t.column "parent_id",   :integer
    t.column "name",        :string
    t.column "description", :text
  end

  add_index "zones", ["parent_id"], :name => "index_zones_on_parent_id"
  add_index "zones", ["name"], :name => "index_zones_on_name"

end
